### ISSUE TITLE
Create a new repository to store required packages for machine provisioning

### ISSUE THREAD

**Issue by giuseppe-carboni** [discos/deployment#315]
We can create a new repository under discos/requirements or a new and locked branch in this repository (deployment) in which we can store all the required packages for the provisioning procedure. @aorlati @marco-buttu this should be briefly discussed when possible.

**Comment by marco-buttu** [comment]
Hi @giuseppe-carboni , "new repository" means local server?

**Comment by giuseppe-carboni** [comment]
@marco-buttu I mean here on github

**Comment by marco-buttu** [comment]
@giuseppe-carboni if the maximum Github allowed space is enough for our packages, then OK :-) All packages have to be open source, and I think they are. Otherwise the repo has to be private.

**Comment by giuseppe-carboni** [comment]
@marco-buttu the maximum allowed space for each file is 100MB, it's actually not enough for our needs. We should come up with a different solution.

**Comment by giuseppe-carboni** [comment]
The new repository has been created, closing the issue.
