### ISSUE TITLE
Solving the ACS warnings during compilation

### ISSUE THREAD

**Issue by aorlati** [discos/deployment#333]
Deployment should solve the annoying warnings we have during DISCOS compilation. 
Here follows an example: 
`/alma/ACS-FEB2017/ACSSW/include/enumpropAlarm.i:156: warning: format ‘%llu’ expects type ‘long long unsigned int’, but argument 6 has type ‘ACS::TimeInterval’`
All that kind of files should be patched during deployment. 
Also this task must be tied to the current version of ACS.

**Comment by giuseppe-carboni** [comment]
Duplicated, take a look at #322, #323.

**Comment by aorlati** [comment]
Ok. Thanks!
