### ISSUE TITLE
Centos 6.8 has reached End of Life

### ISSUE THREAD

**Issue by giuseppe-carboni** [discos/deployment#349]
This means that yum is no longer able to find any package and work properly without applying a patch to the default sources.

**Comment by giuseppe-carboni** [comment]
The repositories we've been using shut down too. We need to find a replacement ASAP

**Comment by fvitello** [comment]
The vault.centos.org repo seems to be ok, and the libselinux-python package is present (https://vault.centos.org/6.10/os/i386/Packages/). Could be an issue related to CA-certs?
