### ISSUE TITLE
error: unknown option single-branch

### ISSUE THREAD

**Issue by fvitello** [discos/deployment#355]
Deployment fails with the following error:

OS CentOS release 6.8 (Final)
git version 2.30.1

> 
> TASK [basie : Execute the basie-get script] ******************************************************************************************************************************
> fatal: [discosdev.inaf.ira.it]: FAILED! => {"changed": true, "cmd": ["./basie-get", "-b"], "delta": "0:00:00.342655", "end": "2021-03-09 13:54:22.770231", "msg": "non-zero return code", "rc": 1, "start": "2021-03-09 13:54:22.427576", "stderr": "error: unknown option single-branch'\nusage: git clone [options] [--] <repo> [<dir>]\n\n    -v, --verbose         be more verbose\n    -q, --quiet           be more quiet\n    --progress            force progress reporting\n    -n, --no-checkout     don't create a checkout\n    --bare                create a bare repository\n    --mirror              create a mirror repository (implies bare)\n    -l, --local           to clone from a local repository\n    --no-hardlinks        don't use local hardlinks, always copy\n    -s, --shared          setup as shared repository\n    --recursive           initialize submodules in the clone\n    --template <path>     path the template repository\n    --reference <repo>    reference repository\n    -o, --origin <branch>\n                          use <branch> instead of 'origin' to track upstream\n    -b, --branch <branch>\n                          checkout <branch> instead of the remote's HEAD\n    -u, --upload-pack <path>\n                          path to git-upload-pack on the remote\n    --depth <depth>       create a shallow clone of that depth\n\nTraceback (most recent call last):\n  File \"./basie-get\", line 69, in <module>\n    cwd=basie_repo_dir\n  File \"/alma/ACS-FEB2017/Python/lib/python2.7/subprocess.py\", line 522, in call\n    return Popen(*popenargs, **kwargs).wait()\n  File \"/alma/ACS-FEB2017/Python/lib/python2.7/subprocess.py\", line 710, in __init__\n    errread, errwrite)\n  File \"/alma/ACS-FEB2017/Python/lib/python2.7/subprocess.py\", line 1335, in _execute_child\n    raise child_exception\nOSError: [Errno 2] No such file or directory: '/discos-sw/basie/basie'", "stderr_lines": ["error: unknown option single-branch'", "usage: git clone [options] [--] <repo> [<dir>]", "", "    -v, --verbose         be more verbose", "    -q, --quiet           be more quiet", "    --progress            force progress reporting", "    -n, --no-checkout     don't create a checkout", "    --bare                create a bare repository", "    --mirror              create a mirror repository (implies bare)", "    -l, --local           to clone from a local repository", "    --no-hardlinks        don't use local hardlinks, always copy", "    -s, --shared          setup as shared repository", "    --recursive           initialize submodules in the clone", "    --template <path>     path the template repository", "    --reference <repo>    reference repository", "    -o, --origin <branch>", "                          use <branch> instead of 'origin' to track upstream", "    -b, --branch <branch>", "                          checkout <branch> instead of the remote's HEAD", "    -u, --upload-pack <path>", "                          path to git-upload-pack on the remote", "    --depth <depth>       create a shallow clone of that depth", "", "Traceback (most recent call last):", "  File \"./basie-get\", line 69, in <module>", "    cwd=basie_repo_dir", "  File \"/alma/ACS-FEB2017/Python/lib/python2.7/subprocess.py\", line 522, in call", "    return Popen(*popenargs, **kwargs).wait()", "  File \"/alma/ACS-FEB2017/Python/lib/python2.7/subprocess.py\", line 710, in __init__", "    errread, errwrite)", "  File \"/alma/ACS-FEB2017/Python/lib/python2.7/subprocess.py\", line 1335, in _execute_child", "    raise child_exception", "OSError: [Errno 2] No such file or directory: '/discos-sw/basie/basie'"], "stdout": "", "stdout_lines": []}
>

**Comment by fvitello** [comment]
The execution  of basie-get -b in a shell seems to work properly:
```
(base) [deploy@discosdev ansible]$ python roles/basie/templates/basie-get -b
Cloning into 'basie'...
remote: Enumerating objects: 1283, done.
remote: Total 1283 (delta 0), reused 0 (delta 0), pack-reused 1283
Receiving objects: 100% (1283/1283), 3.78 MiB | 2.95 MiB/s, done.
Resolving deltas: 100% (880/880), done.

...

running install_scripts
copying build/scripts-2.7/basie -> /home/deploy/miniconda2/bin
changing mode of /home/deploy/miniconda2/bin/basie to 775
running install_egg_info
Writing /home/deploy/miniconda2/lib/python2.7/site-packages/basie-1.0dev-py2.7.egg-info
```

**Comment by fvitello** [comment]
Some further information.

Before to run the deploy i have uninstalled git 1.7 
```
(branch?) discos@discosdev ~ $ git --version
git version 2.30.1
```
After the deployment
```
(branch?) discos@discosdev ~ $ git --version
git version 1.7.1
```

Git appear to be reinstalled from yum on line 77 https://github.com/discos/deployment/blob/master/ansible/roles/acs/tasks/yum.yml

**Comment by giuseppe-carboni** [comment]
@fvitello I don't remember if this was fixed or not. Can the issue be closed?
