### ISSUE TITLE
Install common required yum packages failed

### ISSUE THREAD

**Issue by fvitello** [discos/deployment#362]
Install common required yum packages task fail on CentOS 6.10:

`TASK [yum : Install common required yum packages] ******************************************************************************************************************************************
fatal: [manager.development.inaf.it]: FAILED! => {"changed": false, "changes": {"installed": ["procmail", "subversion", "screen", "ksh", "net-snmp", "telnet", "iperf", "vnstat", "tree"]}, "msg": "Error: Package: rpm-libs-4.8.0-55.el6.i686 (base)\n           Requires: rpm = 4.8.0-55.el6\n           Installed: rpm-4.8.0-59.el6.x86_64 (@base/$releasever)\n               rpm = 4.8.0-59.el6\n           Available: rpm-4.8.0-55.el6.x86_64 (base)\n               rpm = 4.8.0-55.el6\nError: Package: 4:perl-libs-5.10.1-141.el6_7.1.i686 (base)\n           Requires: perl = 4:5.10.1-141.el6_7.1\n           Installed: 4:perl-5.10.1-144.el6.x86_64 (@base/$releasever)\n               perl = 4:5.10.1-144.el6\n           Available: 4:perl-5.10.1-141.el6_7.1.x86_64 (base)\n               perl = 4:5.10.1-141.el6_7.1\nError: Package: glibc-2.12-1.192.el6.i686 (base)\n           Requires: glibc-common = 2.12-1.192.el6\n           Installed: glibc-common-2.12-1.212.el6.x86_64 (@base/$releasever)\n               glibc-common = 2.12-1.212.el6\n           Available: glibc-common-2.12-1.192.el6.x86_64 (base)\n               glibc-common = 2.12-1.192.el6\n", "rc": 1, "results": ["2:vim-enhanced-7.4.629-5.el6_8.1.x86_64 providing vim-enhanced is already installed", "unzip-6.0-5.el6.x86_64 providing unzip is already installed", "openssl-1.0.1e-57.el6.x86_64 providing openssl is already installed", "xterm-253-1.el6.x86_64 providing xterm is already installed", "wget-1.12-10.el6.x86_64 providing wget is already installed", "4:perl-5.10.1-144.el6.x86_64 providing perl is already installed", "rsync-3.0.6-12.el6.x86_64 providing rsync is already installed", "Loaded plugins: fastestmirror, security\nSetting up Install Process\nLoading mirror speeds from cached hostfile\n * epel: d2lzkl7pfhq30w.cloudfront.net\nResolving Dependencies\n--> Running transaction check\n---> Package iperf.x86_64 0:2.0.5-11.el6 will be installed\n---> Package ksh.x86_64 0:20120801-33.el6 will be installed\n---> Package net-snmp.x86_64 1:5.5-57.el6_8.1 will be installed\n--> Processing Dependency: net-snmp-libs = 1:5.5-57.el6_8.1 for package: 1:net-snmp-5.5-57.el6_8.1.x86_64\n---> Package procmail.x86_64 0:3.22-25.1.el6_5.1 will be installed\n---> Package screen.x86_64 0:4.0.3-19.el6 will be installed\n---> Package subversion.x86_64 0:1.6.11-15.el6_7 will be installed\n--> Processing Dependency: perl(URI) >= 1.17 for package: subversion-1.6.11-15.el6_7.x86_64\n---> Package telnet.x86_64 1:0.17-48.el6 will be installed\n---> Package tree.x86_64 0:1.5.3-3.el6 will be installed\n---> Package vnstat.x86_64 0:1.11-1.el6 will be installed\n--> Processing Dependency: libgd.so.2()(64bit) for package: vnstat-1.11-1.el6.x86_64\n--> Running transaction check\n---> Package gd.x86_64 0:2.0.35-11.el6 will be installed\n---> Package net-snmp-libs.i686 1:5.5-57.el6_8.1 will be installed\n--> Processing Dependency: libz.so.1 for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n--> Processing Dependency: libwrap.so.0 for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n--> Processing Dependency: libutil.so.1 for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n--> Processing Dependency: libsensors.so.4 for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n--> Processing Dependency: librpmio.so.1 for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n--> Processing Dependency: librpm.so.1 for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n--> Processing Dependency: libresolv.so.2 for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n--> Processing Dependency: libpthread.so.0(GLIBC_2.2) for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n--> Processing Dependency: libpthread.so.0(GLIBC_2.0) for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n--> Processing Dependency: libpthread.so.0 for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n--> Processing Dependency: libpopt.so.0 for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n--> Processing Dependency: libperl.so for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n--> Processing Dependency: libnsl.so.1 for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n--> Processing Dependency: libm.so.6 for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n--> Processing Dependency: libdl.so.2(GLIBC_2.1) for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n--> Processing Dependency: libdl.so.2(GLIBC_2.0) for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n--> Processing Dependency: libdl.so.2 for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n--> Processing Dependency: libcrypto.so.10(libcrypto.so.10) for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n--> Processing Dependency: libcrypto.so.10(OPENSSL_1.0.1) for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n--> Processing Dependency: libcrypto.so.10 for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n--> Processing Dependency: libcrypt.so.1 for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n--> Processing Dependency: libc.so.6(GLIBC_2.7) for package: 1:net-snmp-libs-5.5-57.el6_8.1.i686\n---> Package perl-URI.noarch 0:1.40-2.el6 will be installed\n--> Running transaction check\n---> Package glibc.i686 0:2.12-1.192.el6 will be installed\n--> Processing Dependency: glibc-common = 2.12-1.192.el6 for package: glibc-2.12-1.192.el6.i686\n--> Processing Dependency: libfreebl3.so(NSSRAWHASH_3.12.3) for package: glibc-2.12-1.192.el6.i686\n--> Processing Dependency: libfreebl3.so for package: glibc-2.12-1.192.el6.i686\n---> Package lm_sensors-libs.i686 0:3.1.1-17.el6 will be installed\n---> Package openssl.i686 0:1.0.1e-48.el6_8.4 will be installed\n--> Processing Dependency: libkrb5.so.3(krb5_3_MIT) for package: openssl-1.0.1e-48.el6_8.4.i686\n--> Processing Dependency: libkrb5.so.3 for package: openssl-1.0.1e-48.el6_8.4.i686\n--> Processing Dependency: libk5crypto.so.3(k5crypto_3_MIT) for package: openssl-1.0.1e-48.el6_8.4.i686\n--> Processing Dependency: libk5crypto.so.3 for package: openssl-1.0.1e-48.el6_8.4.i686\n--> Processing Dependency: libgssapi_krb5.so.2 for package: openssl-1.0.1e-48.el6_8.4.i686\n--> Processing Dependency: libcom_err.so.2 for package: openssl-1.0.1e-48.el6_8.4.i686\n---> Package perl-libs.i686 4:5.10.1-141.el6_7.1 will be installed\n--> Processing Dependency: perl = 4:5.10.1-141.el6_7.1 for package: 4:perl-libs-5.10.1-141.el6_7.1.i686\n---> Package popt.i686 0:1.13-7.el6 will be installed\n---> Package rpm-libs.i686 0:4.8.0-55.el6 will be installed\n--> Processing Dependency: rpm = 4.8.0-55.el6 for package: rpm-libs-4.8.0-55.el6.i686\n--> Processing Dependency: libcap(x86-32) >= 2.16 for package: rpm-libs-4.8.0-55.el6.i686\n--> Processing Dependency: libselinux.so.1 for package: rpm-libs-4.8.0-55.el6.i686\n--> Processing Dependency: libnss3.so(NSS_3.4) for package: rpm-libs-4.8.0-55.el6.i686\n--> Processing Dependency: libnss3.so(NSS_3.2) for package: rpm-libs-4.8.0-55.el6.i686\n--> Processing Dependency: libnss3.so(NSS_3.11.2) for package: rpm-libs-4.8.0-55.el6.i686\n--> Processing Dependency: libnss3.so(NSS_3.10) for package: rpm-libs-4.8.0-55.el6.i686\n--> Processing Dependency: libnss3.so for package: rpm-libs-4.8.0-55.el6.i686\n--> Processing Dependency: libmagic.so.1 for package: rpm-libs-4.8.0-55.el6.i686\n--> Processing Dependency: liblzma.so.0 for package: rpm-libs-4.8.0-55.el6.i686\n--> Processing Dependency: liblua-5.1.so for package: rpm-libs-4.8.0-55.el6.i686\n--> Processing Dependency: libgcc_s.so.1(GCC_3.3.1) for package: rpm-libs-4.8.0-55.el6.i686\n--> Processing Dependency: libgcc_s.so.1(GCC_3.0) for package: rpm-libs-4.8.0-55.el6.i686\n--> Processing Dependency: libgcc_s.so.1 for package: rpm-libs-4.8.0-55.el6.i686\n--> Processing Dependency: libelf.so.1(ELFUTILS_1.1.1) for package: rpm-libs-4.8.0-55.el6.i686\n--> Processing Dependency: libelf.so.1(ELFUTILS_1.0) for package: rpm-libs-4.8.0-55.el6.i686\n--> Processing Dependency: libelf.so.1 for package: rpm-libs-4.8.0-55.el6.i686\n--> Processing Dependency: libdb-4.7.so for package: rpm-libs-4.8.0-55.el6.i686\n--> Processing Dependency: libcap.so.2 for package: rpm-libs-4.8.0-55.el6.i686\n--> Processing Dependency: libbz2.so.1 for package: rpm-libs-4.8.0-55.el6.i686\n--> Processing Dependency: libacl.so.1(ACL_1.0) for package: rpm-libs-4.8.0-55.el6.i686\n--> Processing Dependency: libacl.so.1 for package: rpm-libs-4.8.0-55.el6.i686\n---> Package tcp_wrappers-libs.i686 0:7.6-58.el6 will be installed\n---> Package zlib.i686 0:1.2.3-29.el6 will be installed\n--> Running transaction check\n---> Package bzip2-libs.i686 0:1.0.5-7.el6_0 will be installed\n---> Package db4.i686 0:4.7.25-20.el6_8.1 will be installed\n---> Package elfutils-libelf.i686 0:0.164-2.el6 will be installed\n---> Package file-libs.i686 0:5.04-30.el6 will be installed\n---> Package glibc.i686 0:2.12-1.192.el6 will be installed\n--> Processing Dependency: glibc-common = 2.12-1.192.el6 for package: glibc-2.12-1.192.el6.i686\n---> Package krb5-libs.i686 0:1.10.3-57.el6 will be installed\n--> Processing Dependency: libkeyutils.so.1(KEYUTILS_0.3) for package: krb5-libs-1.10.3-57.el6.i686\n--> Processing Dependency: libkeyutils.so.1 for package: krb5-libs-1.10.3-57.el6.i686\n---> Package libacl.i686 0:2.2.49-6.el6 will be installed\n--> Processing Dependency: libattr.so.1(ATTR_1.0) for package: libacl-2.2.49-6.el6.i686\n--> Processing Dependency: libattr.so.1 for package: libacl-2.2.49-6.el6.i686\n---> Package libcap.i686 0:2.16-5.5.el6 will be installed\n---> Package libcom_err.i686 0:1.41.12-22.el6 will be installed\n---> Package libgcc.i686 0:4.4.7-17.el6 will be installed\n---> Package libselinux.i686 0:2.0.94-7.el6 will be installed\n---> Package lua.i686 0:5.1.4-4.1.el6 will be installed\n--> Processing Dependency: libreadline.so.6 for package: lua-5.1.4-4.1.el6.i686\n--> Processing Dependency: libncurses.so.5 for package: lua-5.1.4-4.1.el6.i686\n---> Package nss.i686 0:3.21.3-2.el6_8 will be installed\n--> Processing Dependency: nss-softokn(x86-32) >= 3.14.3-22 for package: nss-3.21.3-2.el6_8.i686\n--> Processing Dependency: libsoftokn3.so for package: nss-3.21.3-2.el6_8.i686\n--> Processing Dependency: libplds4.so for package: nss-3.21.3-2.el6_8.i686\n--> Processing Dependency: libplc4.so for package: nss-3.21.3-2.el6_8.i686\n--> Processing Dependency: libnssutil3.so(NSSUTIL_3.21) for package: nss-3.21.3-2.el6_8.i686\n--> Processing Dependency: libnssutil3.so(NSSUTIL_3.17.1) for package: nss-3.21.3-2.el6_8.i686\n--> Processing Dependency: libnssutil3.so(NSSUTIL_3.15) for package: nss-3.21.3-2.el6_8.i686\n--> Processing Dependency: libnssutil3.so(NSSUTIL_3.14) for package: nss-3.21.3-2.el6_8.i686\n--> Processing Dependency: libnssutil3.so(NSSUTIL_3.13) for package: nss-3.21.3-2.el6_8.i686\n--> Processing Dependency: libnssutil3.so(NSSUTIL_3.12.5) for package: nss-3.21.3-2.el6_8.i686\n--> Processing Dependency: libnssutil3.so(NSSUTIL_3.12.3) for package: nss-3.21.3-2.el6_8.i686\n--> Processing Dependency: libnssutil3.so(NSSUTIL_3.12) for package: nss-3.21.3-2.el6_8.i686\n--> Processing Dependency: libnssutil3.so for package: nss-3.21.3-2.el6_8.i686\n--> Processing Dependency: libnssdbm3.so for package: nss-3.21.3-2.el6_8.i686\n--> Processing Dependency: libnspr4.so for package: nss-3.21.3-2.el6_8.i686\n---> Package nss-softokn-freebl.i686 0:3.14.3-23.3.el6_8 will be installed\n---> Package perl-libs.i686 4:5.10.1-141.el6_7.1 will be installed\n--> Processing Dependency: perl = 4:5.10.1-141.el6_7.1 for package: 4:perl-libs-5.10.1-141.el6_7.1.i686\n---> Package rpm-libs.i686 0:4.8.0-55.el6 will be installed\n--> Processing Dependency: rpm = 4.8.0-55.el6 for package: rpm-libs-4.8.0-55.el6.i686\n---> Package xz-libs.i686 0:4.999.9-0.5.beta.20091007git.el6 will be installed\n--> Running transaction check\n---> Package glibc.i686 0:2.12-1.192.el6 will be installed\n--> Processing Dependency: glibc-common = 2.12-1.192.el6 for package: glibc-2.12-1.192.el6.i686\n---> Package keyutils-libs.i686 0:1.4-5.el6 will be installed\n---> Package libattr.i686 0:2.4.44-7.el6 will be installed\n---> Package ncurses-libs.i686 0:5.7-4.20090207.el6 will be installed\n---> Package nspr.i686 0:4.11.0-1.el6 will be installed\n---> Package nss-softokn.i686 0:3.14.3-23.3.el6_8 will be installed\n--> Processing Dependency: libsqlite3.so.0 for package: nss-softokn-3.14.3-23.3.el6_8.i686\n---> Package nss-util.i686 0:3.21.3-1.el6_8 will be installed\n---> Package perl-libs.i686 4:5.10.1-141.el6_7.1 will be installed\n--> Processing Dependency: perl = 4:5.10.1-141.el6_7.1 for package: 4:perl-libs-5.10.1-141.el6_7.1.i686\n---> Package readline.i686 0:6.0-4.el6 will be installed\n---> Package rpm-libs.i686 0:4.8.0-55.el6 will be installed\n--> Processing Dependency: rpm = 4.8.0-55.el6 for package: rpm-libs-4.8.0-55.el6.i686\n--> Running transaction check\n---> Package glibc.i686 0:2.12-1.192.el6 will be installed\n--> Processing Dependency: glibc-common = 2.12-1.192.el6 for package: glibc-2.12-1.192.el6.i686\n---> Package perl-libs.i686 4:5.10.1-141.el6_7.1 will be installed\n--> Processing Dependency: perl = 4:5.10.1-141.el6_7.1 for package: 4:perl-libs-5.10.1-141.el6_7.1.i686\n---> Package rpm-libs.i686 0:4.8.0-55.el6 will be installed\n--> Processing Dependency: rpm = 4.8.0-55.el6 for package: rpm-libs-4.8.0-55.el6.i686\n---> Package sqlite.i686 0:3.6.20-1.el6_7.2 will be installed\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"]}`

**Comment by giuseppe-carboni** [comment]
Seems like the culprit is this package `net-snmp-5.5-57.el6.x86_64.rpm`. It also seems that installing the following version fixes the problem `net-snmp-5.5-60.el6.x86_64.rpm`. The package seems to be found [here](http://ftp.iij.ad.jp/pub/linux/centos-vault/6.8/cr/x86_64/Packages/net-snmp-5.5-60.el6.x86_64.rpm).
