### ISSUE TITLE
Get the repository token even if it exists

### ISSUE THREAD

**Issue by marco-buttu** [discos/deployment#391]
In [dependencies/tasks/main.yml](https://github.com/discos/deployment/blob/master/ansible/roles/dependencies/tasks/main.yml) we download the token only if it does not exist. I think that it is the reason of issue #390 (we can not spot the issue if we already have the token, because the _Download the repository token_ rule is not executed when the token exists). I suggest to always execute the _Download the repository token_, no matter if the token exists.

**Comment by giuseppe-carboni** [comment]
Fixed in [ea061d9](https://github.com/discos/deployment/pull/449/commits/ea061d9925417fdcccd166a24450d70f20d5916c)
