### ISSUE TITLE
Issue with boost_python3 lib and SRT minor servo

### ISSUE THREAD

**Issue by aorlati** [discos/deployment#486]
Not really sure wether to post here or in the discos repository.
I'm running a VM

make[2]: *** No rule to make target `-lboost_python3', needed by `/discos-sw/discos/centos_7_compatibility-srt/SRT/Libraries/SRTMinorServoLibrary/src/../lib/libPySRTMinorServoCommandLibrary.so'.  Stop.

@giuseppe-carboni

**Comment by giuseppe-carboni** [comment]
You probably have a VM provisioned before the said issue was resolved [here](https://github.com/discos/deployment/blame/master/ansible/roles/acs/tasks/yum.yml#L77).
You should be able to solve it by running `sudo yum install boost-python36*`.

**Comment by aorlati** [comment]
I confirm that the problem is fixed, needed to update OS repos though (Centos 7 is not supported anymore form July 2024).
I'm closing the issue.

**Comment by aorlati** [comment]
This turned out to be not an issue as it was already addressed previously.
